Won't build on my machine this helps
while making the assets I got this error:
```
scripts/WebComponents.ts:18:37 - error TS2345: Argument of type 'Function' is not assignable to parameter of type 'CustomElementConstructor'.
  Type 'Function' provides no match for the signature 'new (): HTMLElement'.

18  	window.customElements.define(tag, definition)
    	                                  ~~~~~~~~~~


Found 1 error.

make: *** [makefile:38: assets] Error 2
```
I assumed it was meant to get the returned information of the function.
I am not sure but I hope that's it.